Update README to be more accurate
Regression-Games/RGUnityBots pull request #155
Opened 2024-04-10 18:21 UTC by vontell

This is a preliminary PR for improving the README of the Unity package, at least enough to more closely reflect the current state of things. By the end of the month for our MVP launch, this will likely be updated again to have more information.

I might also start a form or table in notion soon for us to name this thing... Regression Games Unity Bots is kind of a mouthful. I wonder if we can find a descriptive name and tagline that gets the idea across but is more memorable.

---

Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446983edfacafa406f1e?pvs=4)

Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the overall PR comment)

- [ ] The code is extensible and backward compatible
- [ ] New public interfaces are extensible and open to backward compatibility in the future
- [ ] If preparing to remove a field in the future (i.e. this PR removes an argument), the argument stays but is no longer functional, and attaches a deprecation warning. A linear task is also created to track this deletion task.
- [ ] Non-critical or potentially modifiable arguments are optional
- [ ] Breaking changes and the approach to handling them have been verified with the team (in the Linear task, design doc, or PR itself)
- [ ] The code is easy to read
- [ ] Unit tests are added for expected and edge cases
- [ ] Integration tests are added for expected and edge cases
- [ ] Functions and classes are documented
- [ ] Migrations for both up and down operations are completed
- [ ] A documentation PR is created and being reviewed for anything in this PR that requires knowledge to use
- [ ] Implications on other dependent code (i.e. sample games and sample bots) is considered, mentioned, and properly handled
- [ ] Style changes and other non-blocking changes are marked as non-blocking from reviewers

2024-04-11 13:11 UTC, RG-nAmKcAz approved these changes

2024-04-11 15:21 UTC, addisonbgross approved these changes

2024-04-11 15:22 UTC, abeizer requested changes

2024-04-11 15:23 UTC, abeizer commented
+1 on brainstorming a new name for this thing. My main motivation for this is that we're focusing on "non-bot" features right now, so the current name feels misleading

2024-04-12 15:14 UTC, abeizer approved these changes

2024-04-12 16:03 UTC, merged