[REG-2222]
Regression-Games/RGUnityBots pull request #376
Opened 2024-12-20 20:59 UTC by abeizer

INSERT_PR_DETAILS_HERE

---

Find the pull request instructions [here](https://www.notion.so/regressiongg/Pull-Request-Process-0d57a7eb582a446983edfacafa406f1e?pvs=4)

Every reviewer and the owner of the PR should consider these points in their request (feel free to copy this checklist so you can fill it out yourself in the overall PR comment)

- [ ] The code is extensible and backward compatible
- [ ] New public interfaces are extensible and open to backward compatibility in the future
- [ ] If preparing to remove a field in the future (i.e. this PR removes an argument), the argument stays but is no longer functional, and attaches a deprecation warning. A linear task is also created to track this deletion task.
- [ ] Non-critical or potentially modifiable arguments are optional
- [ ] Breaking changes and the approach to handling them have been verified with the team (in the Linear task, design doc, or PR itself)
- [ ] The code is easy to read
- [ ] Unit tests are added for expected and edge cases
- [ ] Integration tests are added for expected and edge cases
- [ ] Functions and classes are documented
- [ ] Migrations for both up and down operations are completed
- [ ] A documentation PR is created and being reviewed for anything in this PR that requires knowledge to use
- [ ] Implications on other dependent code (i.e. sample games and sample bots) is considered, mentioned, and properly handled
- [ ] Style changes and other non-blocking changes are marked as non-blocking from reviewers

2025-01-07 15:39 UTC, nAmKcAz requested changes

2025-01-07 15:39 UTC, nAmKcAz commented on src/gg.regression.unity.bots/Runtime/Scripts/ClientDashboard/TcpMessage.cs
> +            StringBuilder sb = new StringBuilder(1000);
make this a readonly threadlocal so we avoid re-allocating/gc'ing it

2025-01-07 15:39 UTC, RG-nAmKcAz commented on src/gg.regression.unity.bots/Runtime/Scripts/ClientDashboard/TcpMessage.cs
> +            StringBuilder sb = new StringBuilder(1000);
make this a readonly threadlocal so we avoid re-allocating/gc'ing it

2025-01-07 15:39 UTC, nAmKcAz commented on src/gg.regression.unity.bots/Runtime/Scripts/ClientDashboard/TcpMessage.cs
> +            StringBuilder sb = new StringBuilder(1000);
make this a readonly threadlocal so we avoid re-allocating/gc'ing it

2025-01-07 15:39 UTC, nAmKcAz commented on src/gg.regression.unity.bots/Runtime/Scripts/ClientDashboard/TcpMessage.cs
> +            StringBuilder sb = new StringBuilder(1000);
make this a readonly threadlocal so we avoid re-allocating/gc'ing it

2025-01-07 15:39 UTC, nAmKcAz commented on src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
> +         * <param name="resourcePath">The segment's resourcePath, if it already exists. If null, a new path will be generated for it.</param>
should probably update this comment to indicate that the resource path should NOT include the '.json' suffix

2025-01-07 15:39 UTC, nAmKcAz commented on src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
> +            if (!resourcePath.StartsWith("Assets/"))
This is only valid if running in the editor.  In built runtime this should point to persistent data path.

2025-01-07 16:14 UTC, abeizer commented on src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
> +            if (!resourcePath.StartsWith("Assets/"))
Deletion isn't allowed during a build right? This should be similar to what we're doing from the overlay currently, just for a segment versus a sequence

2025-01-07 16:18 UTC, RG-nAmKcAz commented on src/gg.regression.unity.bots/Runtime/Scripts/StateRecorder/BotSegments/Models/BotSegment.cs
> +            if (!resourcePath.StartsWith("Assets/"))
If you create a copy/override of a sequence/segment packaged in the build, it is written to the persistent data path.  You CAN delete that override copy.  

There is also an existing code path that deletes the prior existing after writing the new one when renaming.

2025-01-15 17:10 UTC, vontell approved these changes
No changes other than what has already been requested, approving this so we can get these off the notifications list.

2025-03-10 14:57 UTC, closed without merging