[REG-1302] Adds typed `RGActionRequest`s to generated code
Regression-Games/RGUnityBots pull request #56
Opened 2023-10-16 15:19 UTC by RG-nAmKcAz

- Generates new classes extending RGActionRequest for each action to provide typed action requests when coding in C#
- Fixes the issue with namespaces for actions in the action map and in the generated action class
- Sample
```csharp
    public class RGActionRequest_PerformAttack : RGActionRequest
    {
        public RGActionRequest_PerformAttack(bool isEnabled, string actionName, int attackNumber, float damageAmount)
        {
            action = "PerformAttack";
            Input = new ()
            {{"isEnabled", isEnabled}, {"actionName", actionName}, {"attackNumber", attackNumber}, {"damageAmount", damageAmount}, };
        }
    }
```

See also https://github.com/Regression-Games/RegressionDocs/pull/38

2023-10-16 15:37 UTC, vontell requested changes
Looks good! Two requests:

* Is there a PR / docs somewhere so others can use this?
* Is there an example PR that shows what this would look like?

Also, does this have any breaking changes for other usages of the SDK so far in our own samples?

2023-10-16 15:37 UTC, vontell commented on Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
> +                        SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(botAction.Namespace)),
Does this fix the namespace issue I was seeing?

2023-10-16 15:48 UTC, vontell commented on Editor/Scripts/CodeGenerators/GenerateRGActionClasses.cs
> +                        SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(botAction.Namespace)),
Resolved because I see you answer this in the PR description.

2023-10-16 18:58 UTC, rcornwall-reg commented
Does the dev need to know if the actions they're exposing are going to be called by local bots or remote bots? I'm assuming they either a
```
RGActionRequest_PerformAttack
``` 
or a 
```
RGAction_PerformAttack
```
component back to the game object, correct? Or do they always add both?

2023-10-16 18:59 UTC, RG-nAmKcAz commented
@rcornwall-reg `RGActionRequest_PerformAttack` doesn't have to be added to anything, it is used as the request object for queueing an action when writing a bot

2023-10-16 19:17 UTC, vontell approved these changes

2023-10-16 21:52 UTC, rcornwall-reg approved these changes

2023-10-17 11:17 UTC, abeizer approved these changes

2023-10-17 13:14 UTC, merged