[REG-1379] Handle type checks for local unity bots
Regression-Games/RGUnityBots pull request #80
Opened 2023-10-30 18:30 UTC by RG-nAmKcAz

```csharp
                try
                {
                    if (newZeroInput is Vector2 value)
                    {
                        newZero = value;
                    }
                    else
                    {
                        newZero = RGSerialization.Deserialize_Vector2(newZeroInput.ToString());
                    }
                }
                catch (Exception ex)
                {
                    RGDebug.LogError($"Failed to parse 'newZero' - {ex}");
                }

```

2023-10-30 18:52 UTC, addisonbgross approved these changes

2023-10-30 19:32 UTC, rcornwall-reg approved these changes
very nice 👍

2023-10-30 19:44 UTC, abeizer requested changes

2023-10-31 15:55 UTC, RG-nAmKcAz commented
New code doesn't come out formatted cleanly for some reason... Roslyn adds extra spacing on formatting rules with the `or null` added in there... But here it is formatted nicely for you to see

but...
- `nullable`
```csharp
if (newZeroInput is Vector2 or null)
{
    newZero = (Vector2?)newZeroInput;
}
else
{
    newZero = RGSerialization.Deserialize_Vector2_Nullable(newZeroInput.ToString());
}
```

- not so `nullable`
```csharp
if (newZeroInput is Vector2)
{
    newZero = (Vector2)newZeroInput;
}
else
{
    newZero = RGSerialization.Deserialize_Vector2(newZeroInput.ToString());
}
```

2023-10-31 16:04 UTC, vontell approved these changes
Tested and worked for me! Thanks for getting this in!

2023-10-31 16:08 UTC, abeizer approved these changes

2023-10-31 16:31 UTC, merged