[REG-1397] Make SetCharacterConfigFromJson public so user bots can call it
Regression-Games/RGUnityBots pull request #87
Opened 2023-11-02 22:42 UTC by analogrelay

I thought I made `RG.SetCharacterConfigFromJson` a `public` method but I guess not 😩 . Anyway, it needs to be public so that user bots can call it. Our generated Agent Builder code includes a call to `SetCharacterConfigFromJson`:

```csharp
    public class BotEntryPoint : RGBehaviorTreeBot
    {
        protected override bool GetIsSpawnable() => true;
        protected override RGBotLifecycle GetBotLifecycle() => RGBotLifecycle.MANAGED;

        private const string CharacterConfig = @"{}";

        public override void ConfigureBot(RG rgObject)
        {
            rgObject.SetCharacterConfigFromJson(CharacterConfig);
        }

        protected override RootNode BuildBehaviorTree()
        {
            var rootNode = new RootNode();
            rootNode.AddChild(new SequenceNode());

            return rootNode;
        }
    }
```

Also, Rider went ahead and cleaned up some trailing spaces 🤣 . If you turn "Ignore Whitespace" on in the files view, you'll see the only real change.

2023-11-02 22:59 UTC, rcornwall-reg approved these changes
I wonder if there's a way we can create & all share the same IDE auto formatter to prevent odd whitespaces like this

2023-11-03 13:21 UTC, RG-nAmKcAz requested changes
Because we currently have this public in `RG.cs`, the Set methods for it are somewhat redundant.
`public Dictionary<string, object> CharacterConfig = new();`

Option 1:  We can make that be `internal` and have BOTH of the set methods be `public`.  NOTE: This will involve updating the existing Sample bots in RGBossRoom and any other projects with local C# unity bots.

Option 2: We remove both set methods altogether.

2023-11-03 13:59 UTC, vontell approved these changes

2023-11-03 15:31 UTC, analogrelay commented
I agree the internal Set method that takes a Dictionary is redundant, but the one that parses it from JSON is still useful since it internalizes our parsing logic and keeps the bot code from being coupled to Newtonsoft.JSON. I can remove that other internal Set method though.

2023-11-03 15:33 UTC, analogrelay commented
> I wonder if there's a way we can create & all share the same IDE auto formatter to prevent odd whitespaces like this

Rider supports having a settings file that's checked in to the repo and overrides your local user settings. I should be able to configure it with just our basic style settings (so everyone can keep their other settings how they like them). I'll check in to that.

2023-11-03 15:36 UTC, RG-nAmKcAz commented
> I agree the internal Set method that takes a Dictionary is redundant, but the one that parses it from JSON is still useful since it internalizes our parsing logic and keeps the bot code from being coupled to Newtonsoft.JSON. I can remove that other internal Set method though.

I guess I was suggesting that we put the `JsonConvert.DeserializeObject<Dictionary<string, object>>(characterConfigJson)` code into the AgentBuilder generated code itself and remove that Set from string method also.

2023-11-03 15:49 UTC, analogrelay commented
> that we put the JsonConvert.DeserializeObject<Dictionary<string, object>>(characterConfigJson) code into the AgentBuilder generated code itself and remove that Set from string method also.

I think we should isolate Agent Builder generated code from dependencies other than our SDK. If we remove Newtonsoft.JSON someday and a user updates our SDK in their game, all the generated code would break.

2023-11-03 15:50 UTC, analogrelay commented
The generated code is long-lived and while we may make breaking changes that require regenerating, it's best to avoid that when we can. I think keeping the SetFromJson is a good compromise to keep as much compatibility as possible

2023-11-03 15:56 UTC, analogrelay commented
I've made an update to remove the unnecessary `SetCharacterConfig(Dictionary<string, object>)` method. Leaving `SetCharacterConfigFromJson(string)` because I do still think there's value in it.

2023-11-06 14:59 UTC, RG-nAmKcAz approved these changes

2023-11-06 17:15 UTC, merged